Abrisham Examination
alaatv-front/alaatv-front pull request #389
Opened 2023-04-12 22:38 UTC by JasGH

2023-04-15 17:19 UTC, kerasus requested changes

2023-04-15 17:19 UTC, kerasus commented on src/api/models/user.js
> +      liveDescription: '/livedescription?created_at_since=2022-07-09&order_by[]=created_at&order_type[]=desc',
با آقا فرهاد هماهنگ کنید.
احتمالا created_at_since برابر با زمان حال دستگاه کاربر می باشد.

2023-04-15 17:19 UTC, kerasus commented on src/api/models/user.js
> +  getStudyEvents(id) {
default get cache

2023-04-15 17:19 UTC, kerasus commented on src/components/ContentVideoPlayer.vue
> +                          :is-favored="timepointFavored[timepoint.id]"
use ContentTimePoint.isFavored model

2023-04-15 17:19 UTC, kerasus commented on src/components/ContentVideoPlayer.vue
> +                          :loading="bookmarkLoading[timepoint.id]"
use ContentTimePoint.loading model

2023-04-15 17:19 UTC, kerasus commented on src/components/Widgets/User/Abrisham/AbrishamProgress/AbrishamProgress.vue
> +        const response = await this.$apiGateway.set.getContents(this.currentSetId)
rename response

2023-04-17 15:31 UTC, JasGH commented on src/api/models/user.js
> +      liveDescription: '/livedescription?created_at_since=2022-07-09&order_by[]=created_at&order_type[]=desc',
متوجه شدم که در واقع اینطور نیست و ولیو ها باید دقیقا همین باشند

2023-04-18 12:10 UTC, kerasus requested changes

2023-04-18 12:10 UTC, kerasus commented on src/components/Widgets/User/ChatreNejat/ChatreNejatConsulting/ChatreNejatConsulting.vue
> +        const response = await this.$apiGateway.liveDescription.getNewsList(liveDescriptionParams)
rename response

2023-04-18 12:10 UTC, kerasus commented on src/components/Widgets/User/ChatreNejat/ChatreNejatNews/ChatreNejatNews.vue
> +          created_at_since: '2022-07-09',
define in enums

2023-04-18 12:10 UTC, kerasus commented on src/components/Widgets/User/ChatreNejat/ChatreNejatNews/ChatreNejatNews.vue
> +        const response = await this.$apiGateway.liveDescription.getNewsList(liveDescriptionParams)
rename response

2023-04-18 12:10 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +        path: 'https://alaatv.com/api/v2/user/products',
don't use static data

2023-04-18 12:10 UTC, kerasus commented on src/pages/User/DashboardChatreNejat/ProductBookmarks.vue
> +        <content-item class="q-ma-md col-5 col-lg-3"
don't use margin in column

2023-04-18 14:26 UTC, kerasus requested changes

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +  saveComment(data = {
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +  updateComment(data = {
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +  setVideoWatched(data = {
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +  setVideoUnWatched(data = {
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +        return response.data
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +        return response.data.data
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +        return response.data.data
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/content.js
> +        return response.data
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/api/models/product.js
> +        return response.data.data
Object.assign

2023-04-18 14:26 UTC, kerasus commented on src/components/ContentVideoPlayer.vue
> +    currentContentTimepoint () {
define ad method

2023-04-18 14:26 UTC, kerasus commented on src/components/Widgets/User/Abrisham/AbrishamProgress/AbrishamProgress.vue
> +        const lessons = await this.$apiGateway.abrisham.getLessons()
rename lessons

2023-04-18 14:26 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      items: [{}, {}, {}, {}, {}, {}, {}],
?

2023-04-18 14:26 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      const response = await this.getPurchasedProducts()
rename response

2023-04-18 16:59 UTC, kerasus requested changes

2023-04-18 16:59 UTC, kerasus commented on src/api/models/Abrisham.js
> +        return response.data
Object.assign

2023-04-18 16:59 UTC, kerasus commented on src/api/models/LiveDescription.js
> +        return response
Object.assign(response.data)

2023-04-18 16:59 UTC, kerasus commented on src/components/ContentVideoPlayer.vue
get isFavored from response and set in model, then use is_favored instead of isFavored in model

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +        path: '',
remove path: '',

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +        last_page: 1,
remove this

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      await this.setPurchasedProducts()
duplicate code:

      await this.setPurchasedProducts()
      this.filteredProduct = this.products

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      await this.setPurchasedProducts()
duplicate code:

      await this.setPurchasedProducts()
      this.filteredProduct = this.products

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      if (this.products.list.length === 0 || this.products.list[0].sets.list.length === 0) {
check this.products.list.length

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +      this.getSelectedSetContents(set.id).then((contentResponse) => {
rename contentResponse to contents or contentList

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +        this.selectedSet.contents.list = contentResponse.list
this.selectedSet.contents = contentResponse

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +             class="col-12 col-sm-6 col-md-auto col-lg-auto q-ma-md-md q-mb-sm-md flex justify-center">
don't use margin for column

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +  width: 245px;
handle width by grid column

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +    width: 300px;
handle width by grid column

2023-04-18 16:59 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +    margin: 15px;
handle grid space with gutter

2023-04-24 08:01 UTC, kerasus requested changes

2023-04-24 10:23 UTC, kerasus requested changes

2023-04-24 10:23 UTC, kerasus commented on src/components/Widgets/User/MyPurchases/MyPurchases.vue
> +                          style: {
remove this

2023-04-24 12:38 UTC, kerasus requested changes

2023-04-24 13:12 UTC, kerasus approved these changes

2023-04-24 13:12 UTC, merged