capacitor android run Hello World
alaatv-front/alaatv-front pull request #443
Opened 2023-05-03 10:10 UTC by javad9214

2023-05-06 08:49 UTC, kerasus requested changes

2023-05-06 08:49 UTC, kerasus commented on package-lock.json
don't use npm install

2023-05-06 08:49 UTC, kerasus commented on quasar.config.js
use .env ->
linuxAndroidStudio: process.env.LINUX_ANDROID_STUDIO

in .env ->
LINUX_ANDROID_STUDIO=/home/alaa/Downloads/android-studio-2022.2.1.18-linux/android-studio/bin/studio.sh

2023-05-08 08:49 UTC, kerasus commented on .env.example
> +APP_ID=ir.sanatisharif.android.konkur96
rename to ANDROID_APPLICATION_ID

2023-05-08 08:50 UTC, kerasus commented on src-capacitor/android/app/build.gradle
use env

2023-05-08 08:50 UTC, kerasus commented on src-capacitor/android/app/src/main/assets/capacitor.config.json
use env

2023-05-08 08:53 UTC, kerasus commented on src-capacitor/android/variables.gradle
use env

2023-05-08 08:53 UTC, kerasus commented on src-capacitor/capacitor.config.json
use env

2023-05-08 09:09 UTC, javad9214 commented on src-capacitor/android/app/src/main/assets/capacitor.config.json
its can not be happen

2023-05-08 09:09 UTC, javad9214 commented on src-capacitor/capacitor.config.json
its can not be happen

2023-05-08 09:20 UTC, kerasus requested changes

2023-05-08 09:20 UTC, kerasus commented on src-capacitor/capacitor.config.json
use env

2023-05-20 11:49 UTC, closed without merging